__all__ = ["load_model", "FastText"]

from typing import Tuple, List, Dict, Union
import numpy as np

def load_model(path: str) -> FastText: ...

class FastText:
    def batch(self, texts: List[str], k: int = 1, threshold: float = -1.0) -> Tuple[np.ndarray, np.ndarray]: ...
    def get_labels(self) -> Dict[int, str]: ...
    def get_label_by_id(self, id: int) -> Union[None, str]: ...
